export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FAIL="GET_USER_FAIL"

export const USER_LOGOUT_REQUEST="USER_LOGOUT_REQUEST"
export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL="USER_LOGOUT_FAIL"
